### ISSUE TITLE
Enhancement: Use backticks instead of `<code>` for non-html output like markdown

### ISSUE THREAD

**Issue by catesandrew** [jsdoc2md/dmd#30]
Its easier to read markdown with backticks vs a bunch of `<code>` sprawled all over the file in plain text. Again this is a matter of taste when viewing in plain text mode.

Some of the additions to [link.hbs](https://github.com/jsdoc2md/dmd/blob/master/partials/shared/value/link.hbs) are deciding what to wrap each block in: either ` code ` or back tick `` ` ``. Also moved the wrapping in to the template deeper so the type information can all be on the same line when outputting in `list` format.

```hbs
{{! usage: link to="namepath" html=true/false caption="optional caption"~}}

{{~#if html~}}

<code>{{#link to~}}
{{#if url~}}
<a href="{{{url}}}">{{#if ../../caption}}{{../../../caption}}{{else}}{{name}}{{/if}}</a>
{{~else~}}
{{#if ../../caption}}{{../../../caption}}{{else}}{{name}}{{/if~}}
{{/if~}}
{{/link~}}</code>

{{else~}}

`{{#link to~}}
{{#if url~}}
[{{#if ../../caption}}{{escape ../../../caption}}{{else}}{{escape name}}{{/if}}]({{{url}}})
{{~else~}}
{{#if ../../caption}}{{escape ../../../caption}}{{else}}{{escape name}}{{/if~}}
{{/if~}}
{{/link~}}`
{{~/if~}}
```

Also [defaultValue.hbs](https://github.com/jsdoc2md/dmd/blob/master/partials/shared/value/defaultvalue.hbs) would have to be modified. Currently it doesn't have a `{{~#if html~}}` so that would have to be added.

```hbs
{{~#if html~}}
{{#unless (equal defaultvalue undefined)}}<code>{{#if equals}} = {{/if}}{{#if (equal type.names.[0] "string")}}{{json-stringify defaultvalue}}{{else}}{{defaultvalue}}{{/if}}</code>{{/unless}}
{{else~}}
{{#unless (equal defaultvalue undefined)}}`{{#if equals}} = {{/if}}{{#if (equal type.names.[0] "string")}}{{json-stringify defaultvalue}}{{else}}{{defaultvalue}}{{/if}}`{{/unless}}
{{~/if~}}
```

**Comment by 75lb** [comment]
i know it's messy but the `<code>` formatting exists for a reason.. no markdown parser supports mardown-inside-markdown.. e.g. if you have a markdown table, then you cannot use markdown inside it - this code is not valid (the backticks will just be rendered literally): 
```
one | two 
--- | ---
`something` | `in backticks`
```

the only workaround is to use html (`<code>`) inside markdown constructs.

jsdoc2md v2 will have a human-readable output option.

**Comment by catesandrew** [comment]
interesting. i did not know that markdown parsers did not support markdown inside markdown. i switched to using lists because it just doesn't work using tables for a myriad of reasons and didn't run into that issue. face palm!

**Comment by 75lb** [comment]
actually, i have noticed that github have recently started supporting certain inline markdown styles within github tables.. not sure whether npmjs.com supports it yet, will check.. either way, these details (whether to use backticks or `<code>`) will be configurable in jsdoc2md v2..

**Comment by jaydenseric** [comment]
Can we please reopen this, off the back of [this discussion](https://github.com/jsdoc2md/jsdoc-to-markdown/issues/105#issuecomment-261196113)?

Note that the `options.name-format` is [documented wrongly](https://github.com/jsdoc2md/jsdoc-to-markdown/blob/master/docs/API.md) as a string, when in fact it is a boolean. After looking at the source code and and realising this I tried `--name-format true`. Unintuitive, but it turns out just the presence of the flag `--name-format` indicates `true`, and not including it `false`. In the end, it only replaced a tiny portion of the `<code>` tags with backticks, and in places stripped formatting.

I tried `jsdoc2md -t readme-template.hbs src/**/*.js > readme.md -p list -r list && sed -i '' 's/<\\/*code>/`/g' readme.md` to do a follow up regex replacement. Once this worked, it revealed that the nesting of code blocks and links are invalid in the first place. They only seem to work currently due to the mix of HTML and markdown. Once they are in the same format the contents of the code block, expectedly, displayed and not parsed.

```md
**Kind**: static method of <code>[Hurdler](#Hurdler)</code>
```

Should be:

```md
**Kind**: static method of [<code>Hurdler</code>](#Hurdler)
```

Or even better:

```md
**Kind**: static method of [`Hurdler`](#Hurdler)
```

**Comment by 75lb** [comment]
hi, if either of your proposed improvements work on both Github and npmjs.com then i'll gladly accept a patch and make it default, thanks.  @jaydenseric
