### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by jasonk** [jsdoc2md/dmd#89]
I had a whole bunch of source files that caused jsdoc2md to throw `RangeError: Maximum call stack size exceeded.` when I attempted to render them.  I managed to reduce the issue down to this minimal reproduction (with v 5.0.3):

**Foo.js:**
```js
/** */
export class Foo {
  constructor() { }
}
```
**template.hbs:**
```
{{#class name="Foo"}}{{>docs}}{{/class}}
```

**Result:**
```sh
$ jsdoc2md --files ./Foo.js --template ./template.hbs
RangeError: Maximum call stack size exceeded
```

It doesn't appear to matter whether or not there is content in the jsdoc block, it seems like the only things required to trigger it are a doc block before the class and the class must have a constructor.

<details>
  <summary>More info, if it's helpful...</summary>

```sh
$ jsdoc2md --version
5.0.3

$ jsdoc2md --files ./Foo.js --template ./template.hbs --config
{
  "files": [
    "./Foo.js"
  ],
  "template": "./template.hbs"
}

$ jsdoc2md --files ./Foo.js --template ./template.hbs --json
[
  {
    "id": "Foo",
    "longname": "Foo",
    "name": "Foo",
    "kind": "class",
    "scope": "instance",
    "memberof": "Foo",
    "meta": {
      "lineno": 1,
      "filename": "Foo.js",
      "path": "/Users/jasonk/jsdoc2md-repro"
    },
    "order": 0
  }
]

$ jsdoc2md --files ./Foo.js --template ./template.hbs --jsdoc
[
  {
    "comment": "/** */",
    "meta": {
      "range": [
        7,
        44
      ],
      "filename": "Foo.js",
      "lineno": 1,
      "columnno": 7,
      "path": "/Users/jasonk/jsdoc2md-repro",
      "code": {
        "id": "astnode100000002",
        "name": "exports.Foo",
        "type": "ClassDeclaration"
      }
    },
    "name": "Foo",
    "longname": "Foo",
    "kind": "class",
    "scope": "global",
    "undocumented": true
  },
  {
    "comment": "",
    "meta": {
      "range": [
        14,
        44
      ],
      "filename": "Foo.js",
      "lineno": 1,
      "columnno": 14,
      "path": "/Users/jasonk/jsdoc2md-repro",
      "code": {
        "id": "astnode100000003",
        "name": "Foo",
        "type": "ClassDeclaration",
        "paramnames": []
      }
    },
    "undocumented": true,
    "name": "Foo",
    "longname": "Foo",
    "kind": "class",
    "scope": "global"
  },
  {
    "comment": "",
    "meta": {
      "range": [
        26,
        42
      ],
      "filename": "Foo.js",
      "lineno": 1,
      "columnno": 26,
      "path": "/Users/jasonk/jsdoc2md-repro",
      "code": {
        "id": "astnode100000006",
        "name": "exports.Foo",
        "type": "MethodDefinition",
        "paramnames": []
      },
      "vars": {
        "": null
      }
    },
    "undocumented": true,
    "name": "Foo",
    "longname": "Foo#Foo",
    "kind": "class",
    "memberof": "Foo",
    "scope": "instance",
    "params": []
  },
  {
    "comment": "",
    "meta": {
      "range": [
        26,
        42
      ],
      "filename": "Foo.js",
      "lineno": 1,
      "columnno": 26,
      "path": "/Users/jasonk/jsdoc2md-repro",
      "code": {
        "id": "astnode100000006",
        "name": "exports.Foo",
        "type": "MethodDefinition",
        "paramnames": []
      }
    },
    "name": "Foo",
    "longname": "Foo",
    "kind": "class",
    "memberof": "Foo",
    "scope": "instance"
  },
  {
    "kind": "package",
    "longname": "package:undefined",
    "files": [
      "/Users/jasonk/jsdoc2md-repro/Foo.js"
    ]
  }
]
```

</details>

**Comment by 75lb** [comment]
Reproduced - thanks for the reproduction case @jasonk.. It's due this doclet's `id` being equal to `memberof` in the `jsdoc2md --json` output (which comes from jsdoc via jsdoc-parse).. 

```
  {
    "id": "Foo",
    ...
    "memberof": "Foo",
    ...
  }
```

It's at least 10 years since I wrote this app but from memory, the raw jsdoc output is flat, just an array of doclet metadata objects which have no structure.. this was not useful for feeding into a template engine like Handlebars where the output documentation was required to have structure (e.g. module -> exported class -> public/private properties/methods etc).. So the jsdoc-parse module was created to transform jsdoc output into something with structure, where the tree structure is represented using generated, unique doclet `id` values and `memberof` properties pointing to the unique doclet `id` they are a member of.. 

So, in this case the code encounters doclet `id: Foo` then sets about searching for its children (doclets that are `memberof: Foo`).. A child is found (`id: Foo`), so the code checks whether this child has children (doclets with `memberof: Foo`) - it does.. itself.. 

You get the idea - recursive.. Anyway, I'll implement a fix then post again later.

**Comment by 75lb** [comment]
A fix for this is implmemented and will be in the next version.. will post again once that goes live.. In the meantime, you can test the prerelease: 

```
npm install jsdoc-to-markdown@next
```
